GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/info

###
GET http://localhost:3003/api/blogs/62be89a4fec0cfc2a5b67251

###
DELETE http://localhost:3003/api/blogs/62bd2cb17a3bc8cf242e2b72

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "With hardships comes ease",
    "author": "Ahmet Sel",
    "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "likes" : 5
}

###
PUT http://localhost:3003/api/blogs/62be89a4fec0cfc2a5b67251 HTTP/1.1
content-type: application/json

{
    "likes" : 50
}